
#with open('config.yaml', encoding="utf8") as file:
#    cfg = yaml.safe_load(file)

BOT_TOKEN: '6686387629:AAFRu5N7Di4CHpptxdG_rFaQbsvvT_tSnQQ'
GPT_API_KEY: "AQVN31V_Z6wpxVSRe16YXfPitbS-XWB3VZv2pp8I"
FOLDER_ID: "b1g8hv628o86piqpqm02"
SPEECH_KIT_API_KEY: "AQVN1a6-ru21pyEZiU67SKUNbaxvuhaudG5IdOCT"

